version: "3.8"

services:
  lastcallposters:
    image: michaelmishin/expirarr:latest
    container_name: expirarr
    volumes:
      - /tmp/config:/app/config
      - /tmp/data:/app/data
    command: ["python", "-m", "lastcallposters.main"]
