# Required settings
plex:
  url: http://X.X.X.X:32400
  token: your_token_here

maintainerr:
  url: http://X.X.X.X:6246
  api_key: your_api_key_here


# Optional settings
test_mode: false # Set to true to run the script without applying changes to the Plex server. will save changes to a folder called test
run_on_start: true # If true, the application will run once immediately on startup before the scheduler

cron_schedule: "0 0-23/12 * * *" # Default cron schedule to run every 12 hours

badge_customization:
  text_scale: 0.04
  padding_scale: 0.02
  corner_radius_scale: 0.02

text_positioning:
  horizontal_align: left
  vertical_align: bottom
  horizontal_offset_scale: 0.015
  vertical_offset_scale: 0.015
